name: stridelog
description: "Desfrute de uma jornada saudável com nosso app de monitoramento fitness! Registre suas atividades, acompanhe seu progresso e mantenha-se motivado com um design intuitivo e seguro"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 
  remove_alpha_ios: true
